import {normalizeLocale, type CancerId, type SiteLocale} from '@/lib/routes';
import type {AdditionalCancerGuideContent} from '@/lib/additional-cancer-guides';

export type Batch3CancerGuideId =
  | 'neuroblastoma'
  | 'urethral'
  | 'renal-pelvis-ureter'
  | 'salivary-gland'
  | 'nasal-sinus'
  | 'laryngeal'
  | 'parathyroid';

const CONTENT: Record<Batch3CancerGuideId, Record<SiteLocale, AdditionalCancerGuideContent>> = {
  neuroblastoma: {
    en: {
      title: 'Neuroblastoma',
      shortDescription: 'A childhood cancer of immature nerve cells that often begins in an adrenal gland or along the sympathetic nervous system.',
      overviewTitle: 'Understanding neuroblastoma',
      overviewText: 'Neuroblastoma forms in neuroblasts, immature nerve cells that normally develop into parts of the nervous system. It most often affects babies and young children and frequently begins in an adrenal gland, but it can also start in the neck, chest, abdomen or near the spine. Treatment and outlook depend on age, stage, tumour biology and risk group.',
      symptomsTitle: 'Possible signs and symptoms',
      symptoms: ['A lump in the abdomen, neck or chest', 'Persistent bone pain or a limp', 'A swollen abdomen or breathing difficulty in an infant', 'Bulging eyes or dark circles around the eyes', 'Weakness, numbness or reduced movement', 'Unexplained fever, tiredness, bruising or weight loss'],
      treatmentsTitle: 'Treatment and care',
      treatmentsIntro: 'Treatment is planned by a paediatric oncology team according to risk group, age, stage, tumour genetics and response to initial treatment.',
      treatment1: {title: 'Surgery and lower-risk treatment', desc: 'Surgery may be enough for some localised, lower-risk tumours. Some very young infants with selected tumours may be monitored closely because spontaneous regression can occur.'},
      treatment2: {title: 'Multimodal treatment', desc: 'Intermediate- and high-risk disease may require chemotherapy, surgery, radiation therapy, stem-cell rescue, immunotherapy, differentiation therapy or clinical trials.'},
    },
    ro: {
      title: 'Neuroblastom',
      shortDescription: 'Un cancer al copilăriei care apare din celule nervoase imature și începe frecvent într-o glandă suprarenală sau de-a lungul sistemului nervos simpatic.',
      overviewTitle: 'Înțelegerea neuroblastomului',
      overviewText: 'Neuroblastomul se formează din neuroblaste, celule nervoase imature care în mod normal devin părți ale sistemului nervos. Afectează mai ales bebelușii și copiii mici și începe frecvent într-o glandă suprarenală, dar poate apărea și în gât, torace, abdomen ori lângă coloană. Tratamentul și evoluția depind de vârstă, stadiu, biologia tumorii și grupa de risc.',
      symptomsTitle: 'Semne și simptome posibile',
      symptoms: ['Un nodul în abdomen, gât sau torace', 'Durere osoasă persistentă sau șchiopătat', 'Abdomen umflat ori dificultăți de respirație la sugar', 'Ochi proeminenți sau cearcăne închise la culoare', 'Slăbiciune, amorțeală sau mișcare redusă', 'Febră, oboseală, vânătăi ori scădere în greutate fără explicație'],
      treatmentsTitle: 'Tratament și îngrijire',
      treatmentsIntro: 'Tratamentul este planificat de o echipă de oncologie pediatrică în funcție de grupa de risc, vârstă, stadiu, genetica tumorii și răspunsul inițial.',
      treatment1: {title: 'Chirurgie și tratament pentru risc redus', desc: 'Chirurgia poate fi suficientă pentru unele tumori localizate cu risc redus. Unii sugari foarte mici cu tumori selectate pot fi monitorizați atent deoarece poate apărea regresia spontană.'},
      treatment2: {title: 'Tratament multimodal', desc: 'Boala cu risc intermediar sau înalt poate necesita chimioterapie, chirurgie, radioterapie, transplant autolog, imunoterapie, terapie de diferențiere sau studii clinice.'},
    },
    es: {
      title: 'Neuroblastoma',
      shortDescription: 'Un cáncer infantil de células nerviosas inmaduras que suele comenzar en una glándula suprarrenal o a lo largo del sistema nervioso simpático.',
      overviewTitle: 'Comprender el neuroblastoma',
      overviewText: 'El neuroblastoma se forma en neuroblastos, células nerviosas inmaduras que normalmente se convierten en partes del sistema nervioso. Afecta sobre todo a bebés y niños pequeños y suele comenzar en una glándula suprarrenal, aunque también puede aparecer en cuello, tórax, abdomen o cerca de la columna. El tratamiento y pronóstico dependen de edad, etapa, biología tumoral y grupo de riesgo.',
      symptomsTitle: 'Posibles signos y síntomas',
      symptoms: ['Un bulto en abdomen, cuello o tórax', 'Dolor óseo persistente o cojera', 'Abdomen hinchado o dificultad respiratoria en un bebé', 'Ojos saltones u ojeras oscuras', 'Debilidad, entumecimiento o menor movimiento', 'Fiebre, cansancio, moretones o pérdida de peso sin explicación'],
      treatmentsTitle: 'Tratamiento y atención',
      treatmentsIntro: 'El tratamiento lo planifica un equipo de oncología pediátrica según el grupo de riesgo, edad, etapa, genética tumoral y respuesta inicial.',
      treatment1: {title: 'Cirugía y tratamiento de menor riesgo', desc: 'La cirugía puede ser suficiente para algunos tumores localizados de bajo riesgo. Algunos bebés muy pequeños con tumores seleccionados pueden vigilarse porque puede ocurrir regresión espontánea.'},
      treatment2: {title: 'Tratamiento multimodal', desc: 'La enfermedad de riesgo intermedio o alto puede requerir quimioterapia, cirugía, radioterapia, rescate con células madre, inmunoterapia, terapia de diferenciación o ensayos clínicos.'},
    },
  },
  urethral: {
    en: {
      title: 'Urethral Cancer',
      shortDescription: 'A rare cancer that begins in the urethra, the tube carrying urine from the bladder out of the body.',
      overviewTitle: 'Understanding urethral cancer',
      overviewText: 'Urethral cancer begins in cells lining the urethra. Different cell types can be involved, and the location and depth of the tumour strongly affect treatment. It is distinct from bladder cancer, although a history of bladder cancer and chronic urethral inflammation can increase risk.',
      symptomsTitle: 'Possible signs and symptoms',
      symptoms: ['Blood in the urine or bleeding from the urethra', 'Difficulty starting urine flow', 'A weak, interrupted or narrowed urine stream', 'Frequent urination or urinary leakage', 'Discharge from the urethra', 'A lump or thickening in the groin, penis or perineum'],
      treatmentsTitle: 'Treatment and care',
      treatmentsIntro: 'Treatment depends on tumour location, cell type, depth, spread, sex, bladder involvement and overall health. Care often involves urology, oncology and radiation specialists.',
      treatment1: {title: 'Local treatment and surgery', desc: 'Small superficial tumours may be treated with transurethral removal, laser treatment or local excision. Larger or deeper tumours may require more extensive surgery and urinary reconstruction.'},
      treatment2: {title: 'Radiation and systemic treatment', desc: 'Radiation therapy, chemotherapy or combined treatment may be used, particularly for invasive, proximal or recurrent disease. Active surveillance is suitable only in selected situations.'},
    },
    ro: {
      title: 'Cancer uretral',
      shortDescription: 'Un cancer rar care începe în uretră, tubul prin care urina este eliminată din vezică în exteriorul corpului.',
      overviewTitle: 'Înțelegerea cancerului uretral',
      overviewText: 'Cancerul uretral începe în celulele care căptușesc uretra. Pot fi implicate tipuri celulare diferite, iar localizarea și profunzimea tumorii influențează puternic tratamentul. Este diferit de cancerul vezical, deși antecedentele de cancer vezical și inflamația cronică a uretrei pot crește riscul.',
      symptomsTitle: 'Semne și simptome posibile',
      symptoms: ['Sânge în urină sau sângerare din uretră', 'Dificultate la începerea urinării', 'Jet urinar slab, întrerupt sau îngustat', 'Urinări frecvente ori pierderi de urină', 'Secreție din uretră', 'Un nodul sau o îngroșare în zona inghinală, penis ori perineu'],
      treatmentsTitle: 'Tratament și îngrijire',
      treatmentsIntro: 'Tratamentul depinde de localizare, tip celular, profunzime, răspândire, sex, afectarea vezicii și starea generală. Îngrijirea implică frecvent urologie, oncologie și radioterapie.',
      treatment1: {title: 'Tratament local și chirurgie', desc: 'Tumorile superficiale mici pot fi tratate prin rezecție transuretrală, laser sau excizie locală. Tumorile mai mari ori profunde pot necesita chirurgie extinsă și reconstrucție urinară.'},
      treatment2: {title: 'Radioterapie și tratament sistemic', desc: 'Radioterapia, chimioterapia sau tratamentul combinat pot fi folosite mai ales pentru boala invazivă, proximală ori recidivată. Supravegherea activă este potrivită doar în situații selectate.'},
    },
    es: {
      title: 'Cáncer de uretra',
      shortDescription: 'Un cáncer raro que comienza en la uretra, el conducto que lleva la orina desde la vejiga al exterior.',
      overviewTitle: 'Comprender el cáncer de uretra',
      overviewText: 'El cáncer uretral comienza en las células que recubren la uretra. Pueden participar distintos tipos celulares, y la localización y profundidad del tumor influyen mucho en el tratamiento. Es diferente del cáncer de vejiga, aunque los antecedentes de cáncer vesical y la inflamación uretral crónica pueden aumentar el riesgo.',
      symptomsTitle: 'Posibles signos y síntomas',
      symptoms: ['Sangre en la orina o sangrado uretral', 'Dificultad para iniciar el flujo de orina', 'Chorro débil, interrumpido o estrecho', 'Micción frecuente o escapes de orina', 'Secreción de la uretra', 'Un bulto o engrosamiento en ingle, pene o perineo'],
      treatmentsTitle: 'Tratamiento y atención',
      treatmentsIntro: 'El tratamiento depende de la localización, tipo celular, profundidad, extensión, sexo, afectación vesical y estado general. Suele incluir urología, oncología y radioterapia.',
      treatment1: {title: 'Tratamiento local y cirugía', desc: 'Los tumores superficiales pequeños pueden tratarse con resección transuretral, láser o extirpación local. Los tumores mayores o profundos pueden requerir cirugía más extensa y reconstrucción urinaria.'},
      treatment2: {title: 'Radioterapia y tratamiento sistémico', desc: 'La radioterapia, quimioterapia o tratamiento combinado pueden usarse sobre todo en enfermedad invasiva, proximal o recurrente. La vigilancia activa solo es adecuada en situaciones seleccionadas.'},
    },
  },
  'renal-pelvis-ureter': {
    en: {
      title: 'Renal Pelvis and Ureter Cancer',
      shortDescription: 'Upper urinary tract urothelial cancer arising in the renal pelvis or the tube connecting a kidney to the bladder.',
      overviewTitle: 'Understanding upper urinary tract urothelial cancer',
      overviewText: 'This cancer begins in urothelial cells lining the renal pelvis, where urine collects inside the kidney, or the ureter, which carries urine to the bladder. It is related to bladder urothelial cancer but is treated as a distinct upper urinary tract disease. Grade, depth, location and kidney function guide treatment.',
      symptomsTitle: 'Possible signs and symptoms',
      symptoms: ['Blood in the urine', 'Persistent pain in the back, side or flank', 'Painful or frequent urination', 'Unexplained tiredness or weakness', 'Unexplained weight loss', 'A urinary blockage, infection or reduced kidney function'],
      treatmentsTitle: 'Treatment and care',
      treatmentsIntro: 'Treatment depends on grade, stage, tumour number and location, kidney function, bladder history and whether the disease has spread.',
      treatment1: {title: 'Surgery and kidney-sparing treatment', desc: 'Many higher-risk tumours are treated by removing the kidney, ureter and a small cuff of bladder. Selected low-risk tumours may be managed with endoscopic or segmental kidney-sparing procedures.'},
      treatment2: {title: 'Regional and systemic treatment', desc: 'Chemotherapy or immunotherapy may be placed into the upper urinary tract in selected cases or given systemically before or after surgery, or for advanced disease.'},
    },
    ro: {
      title: 'Cancer al pelvisului renal și ureterului',
      shortDescription: 'Cancer urotelial al tractului urinar superior care începe în pelvisul renal sau în tubul ce leagă rinichiul de vezică.',
      overviewTitle: 'Înțelegerea cancerului urotelial al tractului superior',
      overviewText: 'Cancerul începe în celulele uroteliale care căptușesc pelvisul renal, unde se colectează urina în rinichi, sau ureterul, care transportă urina spre vezică. Este înrudit cu cancerul urotelial vezical, dar este tratat ca o boală distinctă a tractului superior. Gradul, profunzimea, localizarea și funcția renală ghidează tratamentul.',
      symptomsTitle: 'Semne și simptome posibile',
      symptoms: ['Sânge în urină', 'Durere persistentă de spate, laterală sau în flanc', 'Urinare dureroasă ori frecventă', 'Oboseală sau slăbiciune inexplicabilă', 'Scădere inexplicabilă în greutate', 'Blocaj urinar, infecție ori reducerea funcției renale'],
      treatmentsTitle: 'Tratament și îngrijire',
      treatmentsIntro: 'Tratamentul depinde de grad, stadiu, numărul și localizarea tumorilor, funcția renală, istoricul vezical și răspândire.',
      treatment1: {title: 'Chirurgie și tratament cu păstrarea rinichiului', desc: 'Multe tumori cu risc înalt sunt tratate prin îndepărtarea rinichiului, ureterului și a unei mici porțiuni de vezică. Unele tumori cu risc redus pot fi tratate endoscopic sau segmentar, păstrând rinichiul.'},
      treatment2: {title: 'Tratament regional și sistemic', desc: 'Chimioterapia sau imunoterapia pot fi administrate local în tractul urinar superior în cazuri selectate ori sistemic înainte sau după operație sau pentru boala avansată.'},
    },
    es: {
      title: 'Cáncer de pelvis renal y uréter',
      shortDescription: 'Cáncer urotelial del tracto urinario superior que comienza en la pelvis renal o el tubo que conecta el riñón con la vejiga.',
      overviewTitle: 'Comprender el cáncer urotelial del tracto superior',
      overviewText: 'Este cáncer comienza en las células uroteliales que recubren la pelvis renal, donde se recoge la orina en el riñón, o el uréter, que la lleva a la vejiga. Está relacionado con el cáncer urotelial vesical, pero se trata como una enfermedad distinta del tracto superior. El grado, profundidad, localización y función renal orientan el tratamiento.',
      symptomsTitle: 'Posibles signos y síntomas',
      symptoms: ['Sangre en la orina', 'Dolor persistente de espalda, costado o flanco', 'Micción dolorosa o frecuente', 'Cansancio o debilidad sin explicación', 'Pérdida de peso sin explicación', 'Obstrucción urinaria, infección o menor función renal'],
      treatmentsTitle: 'Tratamiento y atención',
      treatmentsIntro: 'El tratamiento depende del grado, etapa, número y localización de tumores, función renal, antecedentes vesicales y extensión.',
      treatment1: {title: 'Cirugía y preservación renal', desc: 'Muchos tumores de alto riesgo se tratan retirando riñón, uréter y un pequeño manguito de vejiga. Algunos tumores de bajo riesgo pueden tratarse con procedimientos endoscópicos o segmentarios que preservan el riñón.'},
      treatment2: {title: 'Tratamiento regional y sistémico', desc: 'La quimioterapia o inmunoterapia pueden administrarse localmente en el tracto superior en casos seleccionados o de forma sistémica antes o después de cirugía o para enfermedad avanzada.'},
    },
  },
  'salivary-gland': {
    en: {
      title: 'Salivary Gland Cancer',
      shortDescription: 'A rare group of head and neck cancers that begin in major or minor salivary glands.',
      overviewTitle: 'Understanding salivary gland cancer',
      overviewText: 'Salivary gland cancers can begin in the parotid, submandibular, sublingual or many small salivary glands in the mouth and throat. There are numerous cell types and grades, so pathology review is important. Most salivary gland lumps are not cancer, but persistent or changing symptoms need assessment.',
      symptomsTitle: 'Possible signs and symptoms',
      symptoms: ['A persistent lump near the ear, cheek, jaw, lip or mouth', 'Facial numbness or weakness', 'Persistent facial or jaw pain', 'Difficulty swallowing', 'Difficulty opening the mouth widely', 'Fluid draining from the ear or a neck lump'],
      treatmentsTitle: 'Treatment and care',
      treatmentsIntro: 'Treatment depends on the gland, tumour type and grade, facial-nerve involvement, stage and overall health. A specialist head and neck team should plan care.',
      treatment1: {title: 'Surgery', desc: 'Surgery to remove the tumour and affected gland is the main treatment for many localised cancers. Nearby lymph nodes may also need removal, while preserving nerve function whenever safely possible.'},
      treatment2: {title: 'Radiation and systemic treatment', desc: 'Radiation therapy is often used after surgery for higher-risk disease or when surgery is not possible. Chemotherapy, targeted therapy or trials may be considered for advanced or recurrent cancer.'},
    },
    ro: {
      title: 'Cancer al glandelor salivare',
      shortDescription: 'Un grup rar de cancere ale capului și gâtului care încep în glandele salivare mari sau mici.',
      overviewTitle: 'Înțelegerea cancerului glandelor salivare',
      overviewText: 'Cancerele glandelor salivare pot începe în glanda parotidă, submandibulară, sublinguală sau în numeroase glande mici din gură și gât. Există multe tipuri celulare și grade, astfel încât revizuirea anatomopatologică este importantă. Majoritatea nodulilor salivari nu sunt cancer, dar simptomele persistente ori în schimbare trebuie evaluate.',
      symptomsTitle: 'Semne și simptome posibile',
      symptoms: ['Un nodul persistent lângă ureche, obraz, mandibulă, buză sau în gură', 'Amorțeală sau slăbiciune facială', 'Durere persistentă la nivelul feței ori mandibulei', 'Dificultăți la înghițire', 'Dificultate la deschiderea largă a gurii', 'Lichid care se scurge din ureche ori un nodul la gât'],
      treatmentsTitle: 'Tratament și îngrijire',
      treatmentsIntro: 'Tratamentul depinde de glandă, tipul și gradul tumorii, afectarea nervului facial, stadiu și starea generală. Îngrijirea trebuie planificată de o echipă specializată în cap și gât.',
      treatment1: {title: 'Chirurgie', desc: 'Chirurgia pentru îndepărtarea tumorii și glandei afectate este tratamentul principal pentru multe cancere localizate. Pot fi îndepărtați și ganglioni, păstrând funcția nervilor când este sigur.'},
      treatment2: {title: 'Radioterapie și tratament sistemic', desc: 'Radioterapia este frecvent folosită după operație pentru boala cu risc mai mare sau când chirurgia nu este posibilă. Chimioterapia, terapia țintită ori studiile pot fi luate în considerare pentru boala avansată sau recidivată.'},
    },
    es: {
      title: 'Cáncer de glándulas salivales',
      shortDescription: 'Un grupo raro de cánceres de cabeza y cuello que comienzan en glándulas salivales mayores o menores.',
      overviewTitle: 'Comprender el cáncer de glándulas salivales',
      overviewText: 'Estos cánceres pueden comenzar en las glándulas parótida, submandibular, sublingual o en muchas glándulas pequeñas de boca y garganta. Hay numerosos tipos celulares y grados, por lo que la revisión anatomopatológica es importante. La mayoría de los bultos salivales no son cáncer, pero los síntomas persistentes o cambiantes deben evaluarse.',
      symptomsTitle: 'Posibles signos y síntomas',
      symptoms: ['Un bulto persistente cerca de oreja, mejilla, mandíbula, labio o boca', 'Entumecimiento o debilidad facial', 'Dolor persistente de cara o mandíbula', 'Dificultad para tragar', 'Dificultad para abrir mucho la boca', 'Líquido que sale del oído o un bulto en el cuello'],
      treatmentsTitle: 'Tratamiento y atención',
      treatmentsIntro: 'El tratamiento depende de la glándula, tipo y grado, afectación del nervio facial, etapa y salud general. Debe planificarlo un equipo especializado en cabeza y cuello.',
      treatment1: {title: 'Cirugía', desc: 'La cirugía para retirar el tumor y la glándula afectada es el tratamiento principal de muchos cánceres localizados. También pueden retirarse ganglios, preservando la función nerviosa cuando sea seguro.'},
      treatment2: {title: 'Radioterapia y tratamiento sistémico', desc: 'La radioterapia se usa a menudo después de cirugía para enfermedad de mayor riesgo o cuando no es posible operar. Quimioterapia, terapia dirigida o ensayos pueden considerarse para enfermedad avanzada o recurrente.'},
    },
  },
  'nasal-sinus': {
    en: {
      title: 'Nasal Cavity and Paranasal Sinus Cancer',
      shortDescription: 'Rare head and neck cancers that begin inside the nose or the air-filled sinuses around it.',
      overviewTitle: 'Understanding nasal and sinus cancer',
      overviewText: 'These cancers arise in the nasal cavity or paranasal sinuses. Several cell types can occur, most commonly squamous cell carcinoma. Early symptoms often resemble common sinus problems, and the tumour may be advanced before causing clear signs. Site and pathology determine staging and treatment.',
      symptomsTitle: 'Possible signs and symptoms',
      symptoms: ['A blocked sinus or one-sided nasal obstruction that does not clear', 'Repeated nosebleeds or a persistent runny nose', 'Facial pain, pressure, numbness or swelling', 'A sore or lump inside the nose or on the palate', 'Double vision, eye swelling or another new eye problem', 'Upper-tooth pain, loose teeth or dentures that stop fitting'],
      treatmentsTitle: 'Treatment and care',
      treatmentsIntro: 'Treatment depends on the exact sinus or nasal site, cell type, stage, nearby eye or skull involvement and overall health. A multidisciplinary head and neck team is important.',
      treatment1: {title: 'Surgery and reconstruction', desc: 'Surgery is common and may remove nearby tissue or bone to achieve clear margins. Reconstructive, dental, speech and rehabilitation support may be part of care.'},
      treatment2: {title: 'Radiation and systemic treatment', desc: 'Radiation therapy may be used before, after or instead of surgery. Chemotherapy, chemoradiation, immunotherapy or clinical trials may be recommended according to tumour type and stage.'},
    },
    ro: {
      title: 'Cancer al cavității nazale și sinusurilor paranazale',
      shortDescription: 'Cancere rare ale capului și gâtului care încep în interiorul nasului sau în sinusurile pline cu aer din jur.',
      overviewTitle: 'Înțelegerea cancerului nazal și sinusal',
      overviewText: 'Aceste cancere apar în cavitatea nazală sau sinusurile paranazale. Pot exista mai multe tipuri celulare, cel mai frecvent carcinom scuamos. Simptomele timpurii seamănă adesea cu probleme sinusale obișnuite, iar tumora poate fi avansată înainte de semne clare. Localizarea și anatomopatologia determină stadializarea și tratamentul.',
      symptomsTitle: 'Semne și simptome posibile',
      symptoms: ['Un sinus blocat sau obstrucție nazală unilaterală care nu trece', 'Sângerări nazale repetate ori secreție nazală persistentă', 'Durere, presiune, amorțeală sau umflare facială', 'O rană sau un nodul în nas ori pe cerul gurii', 'Vedere dublă, umflarea ochiului sau altă problemă oculară nouă', 'Durere la dinții superiori, dinți mobili ori proteze care nu se mai potrivesc'],
      treatmentsTitle: 'Tratament și îngrijire',
      treatmentsIntro: 'Tratamentul depinde de sinusul sau zona nazală exactă, tipul celular, stadiu, afectarea ochiului ori craniului și starea generală. Este importantă o echipă multidisciplinară de cap și gât.',
      treatment1: {title: 'Chirurgie și reconstrucție', desc: 'Chirurgia este frecventă și poate îndepărta țesut ori os din apropiere pentru margini libere. Reconstrucția, îngrijirea dentară, logopedia și reabilitarea pot face parte din tratament.'},
      treatment2: {title: 'Radioterapie și tratament sistemic', desc: 'Radioterapia poate fi folosită înainte, după sau în locul operației. Chimioterapia, chimioradioterapia, imunoterapia ori studiile clinice pot fi recomandate în funcție de tip și stadiu.'},
    },
    es: {
      title: 'Cáncer de cavidad nasal y senos paranasales',
      shortDescription: 'Cánceres raros de cabeza y cuello que comienzan dentro de la nariz o en los senos llenos de aire que la rodean.',
      overviewTitle: 'Comprender el cáncer nasal y de senos',
      overviewText: 'Estos cánceres aparecen en la cavidad nasal o los senos paranasales. Pueden surgir varios tipos celulares, con mayor frecuencia carcinoma escamoso. Los síntomas tempranos suelen parecer problemas sinusales comunes y el tumor puede estar avanzado antes de producir señales claras. La localización y patología determinan estadio y tratamiento.',
      symptomsTitle: 'Posibles signos y síntomas',
      symptoms: ['Un seno bloqueado u obstrucción nasal de un lado que no mejora', 'Hemorragias nasales repetidas o secreción persistente', 'Dolor, presión, entumecimiento o hinchazón facial', 'Una llaga o bulto dentro de la nariz o en el paladar', 'Visión doble, hinchazón ocular u otro problema nuevo del ojo', 'Dolor en dientes superiores, dientes flojos o prótesis que dejan de ajustar'],
      treatmentsTitle: 'Tratamiento y atención',
      treatmentsIntro: 'El tratamiento depende del seno o lugar nasal, tipo celular, etapa, afectación del ojo o cráneo y salud general. Es importante un equipo multidisciplinario de cabeza y cuello.',
      treatment1: {title: 'Cirugía y reconstrucción', desc: 'La cirugía es frecuente y puede retirar tejido o hueso cercano para obtener márgenes libres. La reconstrucción, atención dental, logopedia y rehabilitación pueden formar parte del cuidado.'},
      treatment2: {title: 'Radioterapia y tratamiento sistémico', desc: 'La radioterapia puede usarse antes, después o en lugar de cirugía. Quimioterapia, quimiorradioterapia, inmunoterapia o ensayos pueden recomendarse según tipo y etapa.'},
    },
  },
  laryngeal: {
    en: {
      title: 'Laryngeal Cancer',
      shortDescription: 'Cancer arising in the larynx, the voice box containing the vocal cords between the throat and windpipe.',
      overviewTitle: 'Understanding laryngeal cancer',
      overviewText: 'Laryngeal cancer forms in the supraglottis, glottis or subglottis of the voice box. Most are squamous cell cancers. Tobacco and heavy alcohol use are important risk factors, but cancer can occur without them. Treatment aims to control cancer while preserving breathing, swallowing and voice when possible.',
      symptomsTitle: 'Possible signs and symptoms',
      symptoms: ['Hoarseness or a lasting change in voice', 'A sore throat or cough that does not go away', 'Pain or difficulty when swallowing', 'A lump in the neck or throat', 'Persistent ear pain', 'Noisy breathing, breathlessness or coughing blood'],
      treatmentsTitle: 'Treatment and care',
      treatmentsIntro: 'Treatment depends on the part of the larynx, stage, voice and swallowing function, general health and personal priorities. Speech and swallowing specialists are important members of the team.',
      treatment1: {title: 'Radiation or surgery', desc: 'Early cancers may be treated with radiation, laser surgery or partial removal of the larynx. Larger tumours may require more extensive surgery, sometimes including total laryngectomy.'},
      treatment2: {title: 'Combined and systemic treatment', desc: 'Chemoradiation may preserve the larynx in selected advanced cancers. Chemotherapy, immunotherapy or other medicines may be used for recurrent or metastatic disease.'},
    },
    ro: {
      title: 'Cancer laringian',
      shortDescription: 'Cancer care apare în laringe, organul vocii ce conține corzile vocale între gât și trahee.',
      overviewTitle: 'Înțelegerea cancerului laringian',
      overviewText: 'Cancerul laringian se formează în supraglotă, glotă sau subglotă. Majoritatea sunt carcinoame scuamoase. Tutunul și consumul excesiv de alcool sunt factori importanți, dar cancerul poate apărea și fără ei. Tratamentul urmărește controlul bolii și păstrarea respirației, înghițirii și vocii când este posibil.',
      symptomsTitle: 'Semne și simptome posibile',
      symptoms: ['Răgușeală sau schimbare persistentă a vocii', 'Durere în gât sau tuse care nu trece', 'Durere ori dificultate la înghițire', 'Un nodul în gât', 'Durere persistentă de ureche', 'Respirație zgomotoasă, lipsă de aer ori tuse cu sânge'],
      treatmentsTitle: 'Tratament și îngrijire',
      treatmentsIntro: 'Tratamentul depinde de partea laringelui, stadiu, funcția vocii și înghițirii, starea generală și prioritățile persoanei. Logopezii și specialiștii în înghițire sunt importanți.',
      treatment1: {title: 'Radioterapie sau chirurgie', desc: 'Cancerele timpurii pot fi tratate cu radioterapie, laser sau rezecție parțială a laringelui. Tumorile mari pot necesita chirurgie extinsă, uneori laringectomie totală.'},
      treatment2: {title: 'Tratament combinat și sistemic', desc: 'Chimioradioterapia poate păstra laringele în anumite cancere avansate. Chimioterapia, imunoterapia ori alte medicamente pot fi folosite pentru boala recidivată sau metastatică.'},
    },
    es: {
      title: 'Cáncer de laringe',
      shortDescription: 'Cáncer que aparece en la laringe, la caja de la voz que contiene las cuerdas vocales entre garganta y tráquea.',
      overviewTitle: 'Comprender el cáncer de laringe',
      overviewText: 'El cáncer laríngeo se forma en supraglotis, glotis o subglotis. La mayoría son carcinomas escamosos. El tabaco y consumo excesivo de alcohol son factores importantes, aunque puede aparecer sin ellos. El tratamiento busca controlar el cáncer y preservar respiración, deglución y voz cuando sea posible.',
      symptomsTitle: 'Posibles signos y síntomas',
      symptoms: ['Ronquera o cambio persistente de voz', 'Dolor de garganta o tos que no desaparece', 'Dolor o dificultad al tragar', 'Un bulto en cuello o garganta', 'Dolor de oído persistente', 'Respiración ruidosa, falta de aire o tos con sangre'],
      treatmentsTitle: 'Tratamiento y atención',
      treatmentsIntro: 'El tratamiento depende de la parte de la laringe, etapa, función de voz y deglución, salud general y prioridades personales. Logopedas y especialistas en deglución son importantes.',
      treatment1: {title: 'Radioterapia o cirugía', desc: 'Los cánceres tempranos pueden tratarse con radioterapia, láser o extirpación parcial de la laringe. Los tumores grandes pueden requerir cirugía más extensa, a veces laringectomía total.'},
      treatment2: {title: 'Tratamiento combinado y sistémico', desc: 'La quimiorradioterapia puede preservar la laringe en cánceres avanzados seleccionados. Quimioterapia, inmunoterapia u otros medicamentos pueden usarse para enfermedad recurrente o metastásica.'},
    },
  },
  parathyroid: {
    en: {
      title: 'Parathyroid Cancer',
      shortDescription: 'A very rare cancer of a parathyroid gland that often causes excessive parathyroid hormone and high blood calcium.',
      overviewTitle: 'Understanding parathyroid cancer',
      overviewText: 'The small parathyroid glands sit near the thyroid and regulate calcium through parathyroid hormone. Most parathyroid cancer symptoms result from severe hypercalcaemia rather than the neck tumour itself. Parathyroid cancer is distinct from thyroid cancer and from the much more common benign parathyroid adenoma.',
      symptomsTitle: 'Possible signs and symptoms',
      symptoms: ['Marked thirst and frequent urination', 'Weakness, severe tiredness or confusion', 'Nausea, vomiting, poor appetite or constipation', 'Persistent abdominal, side or back pain', 'Bone pain or an unexplained fracture', 'A neck lump, hoarseness or difficulty swallowing'],
      treatmentsTitle: 'Treatment and care',
      treatmentsIntro: 'Treatment must address both the cancer and high calcium levels. Care often involves endocrine surgery, endocrinology, oncology and specialist laboratory monitoring.',
      treatment1: {title: 'Surgery', desc: 'Complete removal of the affected gland and attached nearby tissue in one operation offers the best chance of long-term control when the tumour is resectable.'},
      treatment2: {title: 'Calcium control and additional treatment', desc: 'Medicines, fluids and other measures control hypercalcaemia. Reoperation, radiation, systemic treatment or clinical trials may be considered for recurrent or metastatic disease.'},
    },
    ro: {
      title: 'Cancer paratiroidian',
      shortDescription: 'Un cancer foarte rar al unei glande paratiroide care provoacă frecvent exces de hormon paratiroidian și calciu crescut în sânge.',
      overviewTitle: 'Înțelegerea cancerului paratiroidian',
      overviewText: 'Micile glande paratiroide se află lângă tiroidă și reglează calciul prin hormonul paratiroidian. Majoritatea simptomelor sunt cauzate de hipercalcemia severă, nu de tumora cervicală în sine. Cancerul paratiroidian este diferit de cancerul tiroidian și de adenomul paratiroidian benign, mult mai frecvent.',
      symptomsTitle: 'Semne și simptome posibile',
      symptoms: ['Sete accentuată și urinări frecvente', 'Slăbiciune, oboseală severă sau confuzie', 'Greață, vărsături, poftă redusă ori constipație', 'Durere persistentă abdominală, laterală sau de spate', 'Durere osoasă ori fractură inexplicabilă', 'Un nodul la gât, răgușeală sau dificultăți la înghițire'],
      treatmentsTitle: 'Tratament și îngrijire',
      treatmentsIntro: 'Tratamentul trebuie să controleze atât cancerul, cât și nivelul crescut de calciu. Îngrijirea implică chirurgie endocrină, endocrinologie, oncologie și monitorizare de laborator.',
      treatment1: {title: 'Chirurgie', desc: 'Îndepărtarea completă a glandei afectate împreună cu țesutul apropiat atașat, într-o singură operație, oferă cea mai bună șansă de control pe termen lung când tumora este operabilă.'},
      treatment2: {title: 'Controlul calciului și tratament suplimentar', desc: 'Medicamentele, fluidele și alte măsuri controlează hipercalcemia. Reoperația, radioterapia, tratamentul sistemic ori studiile clinice pot fi luate în considerare pentru boala recidivată sau metastatică.'},
    },
    es: {
      title: 'Cáncer de paratiroides',
      shortDescription: 'Un cáncer muy raro de una glándula paratiroidea que suele causar exceso de hormona paratiroidea y calcio alto en sangre.',
      overviewTitle: 'Comprender el cáncer de paratiroides',
      overviewText: 'Las pequeñas glándulas paratiroides están cerca de la tiroides y regulan el calcio mediante la hormona paratiroidea. La mayoría de síntomas se deben a hipercalcemia grave, no al tumor del cuello. Es distinto del cáncer de tiroides y del adenoma paratiroideo benigno, mucho más frecuente.',
      symptomsTitle: 'Posibles signos y síntomas',
      symptoms: ['Mucha sed y micción frecuente', 'Debilidad, cansancio intenso o confusión', 'Náuseas, vómitos, poco apetito o estreñimiento', 'Dolor persistente abdominal, de costado o espalda', 'Dolor óseo o fractura sin explicación', 'Un bulto en el cuello, ronquera o dificultad para tragar'],
      treatmentsTitle: 'Tratamiento y atención',
      treatmentsIntro: 'El tratamiento debe controlar tanto el cáncer como el calcio elevado. Suele incluir cirugía endocrina, endocrinología, oncología y vigilancia de laboratorio.',
      treatment1: {title: 'Cirugía', desc: 'La extirpación completa de la glándula afectada y el tejido cercano adherido en una sola operación ofrece la mejor posibilidad de control duradero cuando el tumor es resecable.'},
      treatment2: {title: 'Control del calcio y tratamiento adicional', desc: 'Medicamentos, líquidos y otras medidas controlan la hipercalcemia. Reoperación, radioterapia, tratamiento sistémico o ensayos pueden considerarse para enfermedad recurrente o metastásica.'},
    },
  },
};

export function getAdditionalCancerGuideBatch3Content(
  cancerId: CancerId | string,
  localeInput: string,
): AdditionalCancerGuideContent | undefined {
  if (!(cancerId in CONTENT)) return undefined;
  const locale = normalizeLocale(localeInput);
  return CONTENT[cancerId as Batch3CancerGuideId][locale];
}
