import {normalizeLocale, type CancerId, type SiteLocale} from '@/lib/routes';
import type {AdditionalCancerGuideContent} from '@/lib/additional-cancer-guides';

export type Batch2CancerGuideId =
  | 'adrenal'
  | 'primary-peritoneal'
  | 'fallopian-tube'
  | 'unknown-primary'
  | 'gestational-trophoblastic'
  | 'mds'
  | 'mpn';

const CONTENT: Record<Batch2CancerGuideId, Record<SiteLocale, AdditionalCancerGuideContent>> = {
  adrenal: {
    en: {
      title: 'Adrenocortical Carcinoma',
      shortDescription: 'A rare cancer that begins in the hormone-producing outer layer of an adrenal gland.',
      overviewTitle: 'Understanding adrenal cortex cancer',
      overviewText: 'Adrenocortical carcinoma begins in the cortex, the outer part of an adrenal gland above the kidney. Some tumours make excess cortisol, aldosterone, testosterone or oestrogen and cause hormone-related symptoms; others do not. It is different from pheochromocytoma, which begins in the inner adrenal medulla.',
      symptomsTitle: 'Possible signs and symptoms',
      symptoms: ['A lump, pain or fullness in the abdomen', 'Persistent back or side pain', 'New or difficult-to-control high blood pressure', 'Muscle weakness, cramps or frequent urination', 'Unusual weight, blood-sugar or body-shape changes', 'Unexpected menstrual, hair, voice, breast or sexual changes'],
      treatmentsTitle: 'Treatment and care',
      treatmentsIntro: 'Treatment depends on stage, hormone production, whether the tumour can be completely removed and overall health. Care usually involves endocrine and oncology specialists.',
      treatment1: {title: 'Surgery', desc: 'Removal of the affected adrenal gland is the main treatment when the cancer can be safely removed. Nearby tissue or lymph nodes may also need treatment.'},
      treatment2: {title: 'Medicines and other treatment', desc: 'Mitotane, chemotherapy, radiation therapy or clinical trials may be considered for higher-risk, unresectable, metastatic or recurrent disease. Excess hormone production also needs specific management.'},
    },
    ro: {
      title: 'Carcinom corticosuprarenal',
      shortDescription: 'Un cancer rar care începe în stratul extern al glandei suprarenale, responsabil de producerea hormonilor.',
      overviewTitle: 'Înțelegerea cancerului corticosuprarenal',
      overviewText: 'Carcinomul corticosuprarenal începe în cortex, partea externă a glandei suprarenale situate deasupra rinichiului. Unele tumori produc în exces cortizol, aldosteron, testosteron sau estrogen și provoacă simptome hormonale; altele nu. Este diferit de feocromocitom, care începe în medulosuprarenală.',
      symptomsTitle: 'Semne și simptome posibile',
      symptoms: ['Un nodul, durere sau senzație de plenitudine în abdomen', 'Durere persistentă de spate sau laterală', 'Tensiune arterială nou apărută sau greu de controlat', 'Slăbiciune musculară, crampe sau urinări frecvente', 'Schimbări neobișnuite ale greutății, glicemiei sau formei corpului', 'Schimbări neașteptate ale menstruației, părului, vocii, sânilor sau funcției sexuale'],
      treatmentsTitle: 'Tratament și îngrijire',
      treatmentsIntro: 'Tratamentul depinde de stadiu, producția hormonală, posibilitatea îndepărtării complete și starea generală. Îngrijirea implică de obicei specialiști în endocrinologie și oncologie.',
      treatment1: {title: 'Chirurgie', desc: 'Îndepărtarea glandei suprarenale afectate este tratamentul principal atunci când cancerul poate fi operat în siguranță. Pot fi tratate și țesuturile ori ganglionii din apropiere.'},
      treatment2: {title: 'Medicamente și alte tratamente', desc: 'Mitotanul, chimioterapia, radioterapia sau studiile clinice pot fi luate în considerare pentru boala cu risc mai mare, inoperabilă, metastatică ori recidivată. Excesul hormonal necesită și tratament specific.'},
    },
    es: {
      title: 'Carcinoma corticosuprarrenal',
      shortDescription: 'Un cáncer raro que comienza en la capa externa productora de hormonas de una glándula suprarrenal.',
      overviewTitle: 'Comprender el cáncer de la corteza suprarrenal',
      overviewText: 'El carcinoma corticosuprarrenal comienza en la corteza, la parte externa de la glándula suprarrenal situada sobre el riñón. Algunos tumores producen demasiado cortisol, aldosterona, testosterona o estrógeno y causan síntomas hormonales; otros no. Es distinto del feocromocitoma, que comienza en la médula suprarrenal.',
      symptomsTitle: 'Posibles signos y síntomas',
      symptoms: ['Un bulto, dolor o sensación de llenura abdominal', 'Dolor persistente de espalda o costado', 'Presión arterial nueva o difícil de controlar', 'Debilidad muscular, calambres o micción frecuente', 'Cambios inusuales de peso, glucosa o forma corporal', 'Cambios inesperados en menstruación, vello, voz, mamas o función sexual'],
      treatmentsTitle: 'Tratamiento y atención',
      treatmentsIntro: 'El tratamiento depende de la etapa, la producción hormonal, si el tumor puede extirparse por completo y el estado general. La atención suele incluir especialistas en endocrinología y oncología.',
      treatment1: {title: 'Cirugía', desc: 'La extirpación de la glándula suprarrenal afectada es el tratamiento principal cuando el cáncer puede retirarse de forma segura. También pueden tratarse tejidos o ganglios cercanos.'},
      treatment2: {title: 'Medicamentos y otros tratamientos', desc: 'Mitotano, quimioterapia, radioterapia o ensayos clínicos pueden considerarse para enfermedad de mayor riesgo, no resecable, metastásica o recurrente. El exceso hormonal también necesita tratamiento específico.'},
    },
  },
  'primary-peritoneal': {
    en: {
      title: 'Primary Peritoneal Cancer',
      shortDescription: 'Cancer that begins in the tissue lining the abdomen and is closely related to epithelial ovarian and fallopian tube cancer.',
      overviewTitle: 'Understanding primary peritoneal cancer',
      overviewText: 'Primary peritoneal cancer begins in the peritoneum, the thin tissue lining the abdominal cavity and covering many abdominal organs. It forms in the same kind of tissue as epithelial ovarian and fallopian tube cancers and is generally staged and treated in a similar way. It can occur even when the ovaries appear normal or have previously been removed.',
      symptomsTitle: 'Possible signs and symptoms',
      symptoms: ['Persistent abdominal or pelvic pain', 'Bloating, swelling or increasing abdominal size', 'Feeling full quickly or difficulty eating', 'Urinary urgency or frequent urination', 'Constipation, gas or another lasting bowel change', 'Unexplained weight change or persistent fatigue'],
      treatmentsTitle: 'Treatment and care',
      treatmentsIntro: 'Treatment depends on disease extent, pathology, overall health and tumour biomarkers. A gynaecological oncology team usually coordinates care.',
      treatment1: {title: 'Surgery and chemotherapy', desc: 'Treatment commonly combines surgery to remove as much visible cancer as possible with platinum-based chemotherapy. The order depends on whether surgery is appropriate at diagnosis.'},
      treatment2: {title: 'Targeted and maintenance treatment', desc: 'Bevacizumab, PARP inhibitors or other treatments may be used in selected cases according to response, inherited or tumour gene findings and recurrence pattern.'},
    },
    ro: {
      title: 'Cancer peritoneal primar',
      shortDescription: 'Cancer care începe în țesutul ce căptușește abdomenul și este strâns înrudit cu cancerul ovarian epitelial și al trompei uterine.',
      overviewTitle: 'Înțelegerea cancerului peritoneal primar',
      overviewText: 'Cancerul peritoneal primar începe în peritoneu, țesutul subțire care căptușește cavitatea abdominală și acoperă multe organe. Se formează în același tip de țesut ca tumorile ovariene epiteliale și ale trompelor uterine și este de obicei stadializat și tratat asemănător. Poate apărea chiar dacă ovarele par normale sau au fost îndepărtate anterior.',
      symptomsTitle: 'Semne și simptome posibile',
      symptoms: ['Durere abdominală sau pelvină persistentă', 'Balonare, umflare sau creșterea dimensiunii abdomenului', 'Sațietate rapidă sau dificultăți la alimentație', 'Nevoie urgentă ori frecventă de a urina', 'Constipație, gaze sau altă schimbare persistentă a tranzitului', 'Schimbare inexplicabilă în greutate ori oboseală persistentă'],
      treatmentsTitle: 'Tratament și îngrijire',
      treatmentsIntro: 'Tratamentul depinde de extindere, anatomopatologie, starea generală și biomarkerii tumorali. Îngrijirea este coordonată de obicei de o echipă de oncologie ginecologică.',
      treatment1: {title: 'Chirurgie și chimioterapie', desc: 'Tratamentul combină frecvent chirurgia pentru îndepărtarea cât mai multor leziuni vizibile cu chimioterapia pe bază de platină. Ordinea depinde de oportunitatea operației la diagnostic.'},
      treatment2: {title: 'Tratament țintit și de întreținere', desc: 'Bevacizumab, inhibitorii PARP sau alte tratamente pot fi folosite în cazuri selectate, în funcție de răspuns, modificările genetice moștenite ori tumorale și modelul recidivei.'},
    },
    es: {
      title: 'Cáncer peritoneal primario',
      shortDescription: 'Cáncer que comienza en el tejido que recubre el abdomen y está estrechamente relacionado con el cáncer epitelial de ovario y trompa de Falopio.',
      overviewTitle: 'Comprender el cáncer peritoneal primario',
      overviewText: 'El cáncer peritoneal primario comienza en el peritoneo, el tejido fino que recubre la cavidad abdominal y cubre muchos órganos. Se forma en el mismo tipo de tejido que los cánceres epiteliales de ovario y trompa de Falopio y suele clasificarse y tratarse de forma similar. Puede aparecer aunque los ovarios parezcan normales o hayan sido extirpados.',
      symptomsTitle: 'Posibles signos y síntomas',
      symptoms: ['Dolor abdominal o pélvico persistente', 'Hinchazón o aumento del tamaño abdominal', 'Llenura rápida o dificultad para comer', 'Urgencia o frecuencia urinaria', 'Estreñimiento, gases u otro cambio intestinal persistente', 'Cambio de peso sin explicación o cansancio persistente'],
      treatmentsTitle: 'Tratamiento y atención',
      treatmentsIntro: 'El tratamiento depende de la extensión, la anatomía patológica, el estado general y los biomarcadores. Un equipo de oncología ginecológica suele coordinar la atención.',
      treatment1: {title: 'Cirugía y quimioterapia', desc: 'El tratamiento combina con frecuencia cirugía para retirar la mayor cantidad posible de cáncer visible con quimioterapia basada en platino. El orden depende de si la cirugía es adecuada al diagnóstico.'},
      treatment2: {title: 'Tratamiento dirigido y de mantenimiento', desc: 'Bevacizumab, inhibidores de PARP u otros tratamientos pueden utilizarse en casos seleccionados según la respuesta, los hallazgos genéticos heredados o tumorales y el patrón de recurrencia.'},
    },
  },
  'fallopian-tube': {
    en: {
      title: 'Fallopian Tube Cancer',
      shortDescription: 'A rare gynaecological cancer that begins in a fallopian tube and is treated similarly to epithelial ovarian cancer.',
      overviewTitle: 'Understanding fallopian tube cancer',
      overviewText: 'Fallopian tube cancer begins in one of the tubes connecting the ovaries to the uterus. Many high-grade serous cancers previously labelled ovarian may begin near the fimbrial end of a fallopian tube. Fallopian tube, epithelial ovarian and primary peritoneal cancers arise from similar tissue and share staging and treatment approaches.',
      symptomsTitle: 'Possible signs and symptoms',
      symptoms: ['Persistent pelvic or abdominal pain', 'Bloating or abdominal swelling', 'Feeling full quickly or reduced appetite', 'Unusual vaginal bleeding or watery discharge', 'Urinary urgency or frequent urination', 'A pelvic lump or persistent bowel change'],
      treatmentsTitle: 'Treatment and care',
      treatmentsIntro: 'Treatment depends on stage, pathology, fertility considerations, inherited risk and tumour biomarkers. Care is usually provided by a gynaecological oncologist.',
      treatment1: {title: 'Surgery and staging', desc: 'Surgery commonly removes the uterus, both fallopian tubes and ovaries, omentum and visible disease, with careful staging. More limited surgery may be appropriate only in selected situations.'},
      treatment2: {title: 'Chemotherapy and targeted treatment', desc: 'Platinum-based chemotherapy is often used. Targeted or maintenance treatments, including PARP inhibitors in suitable cases, depend on response and molecular findings.'},
    },
    ro: {
      title: 'Cancer al trompei uterine',
      shortDescription: 'Un cancer ginecologic rar care începe într-o trompă uterină și este tratat asemănător cancerului ovarian epitelial.',
      overviewTitle: 'Înțelegerea cancerului trompei uterine',
      overviewText: 'Cancerul trompei uterine începe într-una dintre trompele care leagă ovarele de uter. Multe cancere seroase de grad înalt etichetate anterior drept ovariene pot începe lângă capătul fimbrial al trompei. Cancerele trompei, ovarului epitelial și peritoneului primar provin din țesuturi similare și au abordări comune de stadializare și tratament.',
      symptomsTitle: 'Semne și simptome posibile',
      symptoms: ['Durere pelvină sau abdominală persistentă', 'Balonare ori umflare abdominală', 'Sațietate rapidă sau poftă de mâncare redusă', 'Sângerare vaginală neobișnuită ori secreție apoasă', 'Nevoie urgentă sau frecventă de a urina', 'Un nodul pelvin ori o schimbare persistentă a tranzitului'],
      treatmentsTitle: 'Tratament și îngrijire',
      treatmentsIntro: 'Tratamentul depinde de stadiu, anatomopatologie, fertilitate, riscul ereditar și biomarkerii tumorali. Îngrijirea este oferită de obicei de un oncolog ginecolog.',
      treatment1: {title: 'Chirurgie și stadializare', desc: 'Operația îndepărtează frecvent uterul, ambele trompe și ovare, epiploonul și leziunile vizibile, cu stadializare atentă. Chirurgia limitată este potrivită doar în situații selectate.'},
      treatment2: {title: 'Chimioterapie și tratament țintit', desc: 'Chimioterapia pe bază de platină este folosită frecvent. Tratamentele țintite ori de întreținere, inclusiv inhibitorii PARP în cazuri potrivite, depind de răspuns și de rezultatele moleculare.'},
    },
    es: {
      title: 'Cáncer de trompa de Falopio',
      shortDescription: 'Un cáncer ginecológico raro que comienza en una trompa de Falopio y se trata de forma similar al cáncer epitelial de ovario.',
      overviewTitle: 'Comprender el cáncer de trompa de Falopio',
      overviewText: 'El cáncer de trompa de Falopio comienza en uno de los conductos que conectan los ovarios con el útero. Muchos cánceres serosos de alto grado antes considerados ováricos pueden comenzar cerca del extremo fimbrial de la trompa. Los cánceres de trompa, ovario epitelial y peritoneo primario surgen de tejidos similares y comparten estadificación y tratamiento.',
      symptomsTitle: 'Posibles signos y síntomas',
      symptoms: ['Dolor pélvico o abdominal persistente', 'Hinchazón abdominal', 'Llenura rápida o menor apetito', 'Sangrado vaginal inusual o secreción acuosa', 'Urgencia o frecuencia urinaria', 'Un bulto pélvico o cambio intestinal persistente'],
      treatmentsTitle: 'Tratamiento y atención',
      treatmentsIntro: 'El tratamiento depende de la etapa, anatomía patológica, fertilidad, riesgo hereditario y biomarcadores tumorales. Suele estar a cargo de oncología ginecológica.',
      treatment1: {title: 'Cirugía y estadificación', desc: 'La cirugía suele retirar el útero, ambas trompas y ovarios, el epiplón y la enfermedad visible, con estadificación cuidadosa. La cirugía limitada solo es adecuada en situaciones seleccionadas.'},
      treatment2: {title: 'Quimioterapia y tratamiento dirigido', desc: 'Se usa con frecuencia quimioterapia basada en platino. Los tratamientos dirigidos o de mantenimiento, incluidos inhibidores de PARP en casos apropiados, dependen de la respuesta y los hallazgos moleculares.'},
    },
  },
  'unknown-primary': {
    en: {
      title: 'Cancer of Unknown Primary (CUP)',
      shortDescription: 'Metastatic cancer confirmed by biopsy when the place where it first began cannot be identified after evaluation.',
      overviewTitle: 'Understanding cancer of unknown primary',
      overviewText: 'CUP is diagnosed when cancer is found in one or more parts of the body but tests do not establish its original site. It is not a single cancer type: pathology, imaging, clinical pattern and molecular tests are used to identify the most likely tumour family and treatments that may work. Sometimes the primary site remains unknown.',
      symptomsTitle: 'Possible signs and symptoms',
      symptoms: ['A persistent or enlarging lump', 'Unexplained bone, abdominal or chest pain', 'A lasting cough or shortness of breath', 'Abdominal swelling or a persistent bowel change', 'New neurological symptoms such as weakness or headaches', 'Unexplained weight loss, fever or fatigue'],
      treatmentsTitle: 'Treatment and care',
      treatmentsIntro: 'Treatment is based on pathology, where the cancer has spread, molecular findings, likely tissue of origin, overall health and whether the presentation belongs to a favourable subgroup.',
      treatment1: {title: 'Site-directed or local treatment', desc: 'When tests strongly suggest a particular cancer type, treatment may follow that pathway. Surgery or radiation may be used for isolated or limited disease and certain favourable presentations.'},
      treatment2: {title: 'Systemic treatment', desc: 'Chemotherapy, immunotherapy or targeted therapy may be used according to tumour features and biomarkers. Supportive and palliative care are part of treatment planning.'},
    },
    ro: {
      title: 'Cancer cu origine necunoscută (CUP)',
      shortDescription: 'Cancer metastatic confirmat prin biopsie, când locul în care a început nu poate fi identificat după evaluare.',
      overviewTitle: 'Înțelegerea cancerului cu origine necunoscută',
      overviewText: 'CUP este diagnosticat când cancerul este găsit în una sau mai multe zone, dar investigațiile nu stabilesc locul de origine. Nu este un singur tip de cancer: anatomopatologia, imagistica, modelul clinic și testele moleculare sunt folosite pentru a identifica familia tumorală probabilă și tratamentele potrivite. Uneori originea rămâne necunoscută.',
      symptomsTitle: 'Semne și simptome posibile',
      symptoms: ['Un nodul persistent sau în creștere', 'Durere osoasă, abdominală ori toracică inexplicabilă', 'Tuse persistentă sau lipsă de aer', 'Umflare abdominală ori schimbare persistentă a tranzitului', 'Simptome neurologice noi, precum slăbiciune sau dureri de cap', 'Scădere inexplicabilă în greutate, febră ori oboseală'],
      treatmentsTitle: 'Tratament și îngrijire',
      treatmentsIntro: 'Tratamentul se bazează pe anatomopatologie, localizarea metastazelor, rezultatele moleculare, țesutul de origine probabil, starea generală și apartenența la un subgrup favorabil.',
      treatment1: {title: 'Tratament orientat după origine sau local', desc: 'Când investigațiile sugerează puternic un anumit tip de cancer, tratamentul poate urma acea cale. Chirurgia ori radioterapia pot fi folosite pentru boală izolată sau limitată și pentru anumite prezentări favorabile.'},
      treatment2: {title: 'Tratament sistemic', desc: 'Chimioterapia, imunoterapia sau terapia țintită pot fi folosite în funcție de caracteristicile tumorii și biomarkeri. Îngrijirea de susținere și paliativă face parte din plan.'},
    },
    es: {
      title: 'Cáncer de origen primario desconocido (CUP)',
      shortDescription: 'Cáncer metastásico confirmado por biopsia cuando no se identifica el lugar donde comenzó tras la evaluación.',
      overviewTitle: 'Comprender el cáncer de origen desconocido',
      overviewText: 'El CUP se diagnostica cuando se encuentra cáncer en una o más zonas, pero las pruebas no establecen su lugar de origen. No es un único tipo: anatomía patológica, imágenes, patrón clínico y pruebas moleculares se utilizan para identificar la familia tumoral probable y tratamientos útiles. A veces el origen nunca se encuentra.',
      symptomsTitle: 'Posibles signos y síntomas',
      symptoms: ['Un bulto persistente o creciente', 'Dolor óseo, abdominal o torácico sin explicación', 'Tos duradera o falta de aire', 'Hinchazón abdominal o cambio intestinal persistente', 'Síntomas neurológicos nuevos, como debilidad o cefalea', 'Pérdida de peso, fiebre o cansancio sin explicación'],
      treatmentsTitle: 'Tratamiento y atención',
      treatmentsIntro: 'El tratamiento se basa en la anatomía patológica, dónde se ha diseminado, hallazgos moleculares, tejido de origen probable, estado general y si pertenece a un subgrupo favorable.',
      treatment1: {title: 'Tratamiento dirigido al origen o local', desc: 'Cuando las pruebas sugieren un tipo concreto, el tratamiento puede seguir esa vía. La cirugía o radioterapia pueden utilizarse para enfermedad aislada o limitada y algunas presentaciones favorables.'},
      treatment2: {title: 'Tratamiento sistémico', desc: 'Quimioterapia, inmunoterapia o terapia dirigida pueden usarse según las características y biomarcadores. Los cuidados de apoyo y paliativos forman parte del plan.'},
    },
  },
  'gestational-trophoblastic': {
    en: {
      title: 'Gestational Trophoblastic Disease (GTD)',
      shortDescription: 'A group of rare conditions caused by abnormal trophoblast growth in the uterus after conception.',
      overviewTitle: 'Understanding gestational trophoblastic disease',
      overviewText: 'GTD includes hydatidiform mole and malignant forms collectively called gestational trophoblastic neoplasia, such as invasive mole and choriocarcinoma. These conditions arise from pregnancy-related trophoblast cells. Blood hCG levels are central to diagnosis and follow-up, and treatment differs from typical uterine cancer.',
      symptomsTitle: 'Possible signs and symptoms',
      symptoms: ['Abnormal vaginal bleeding during or after pregnancy', 'A uterus larger than expected for the pregnancy', 'Pelvic pain or pressure', 'Severe nausea and vomiting', 'Very early high blood pressure with headache or swelling', 'Persistent bleeding, breathlessness, dizziness or marked fatigue after pregnancy'],
      treatmentsTitle: 'Treatment and care',
      treatmentsIntro: 'Treatment depends on the exact GTD type, hCG level, spread, previous pregnancy and future fertility wishes. Specialist follow-up is essential until hCG monitoring is complete.',
      treatment1: {title: 'Uterine evacuation and monitoring', desc: 'A molar pregnancy is usually treated by removing the abnormal tissue from the uterus, followed by regular hCG tests to confirm that trophoblastic cells are no longer active.'},
      treatment2: {title: 'Chemotherapy or surgery', desc: 'Gestational trophoblastic neoplasia is commonly treated with one or more chemotherapy medicines. Surgery or other treatment may be used in selected resistant, recurrent or specialised cases.'},
    },
    ro: {
      title: 'Boală trofoblastică gestațională (BTG)',
      shortDescription: 'Un grup de afecțiuni rare cauzate de creșterea anormală a celulelor trofoblastice în uter după concepție.',
      overviewTitle: 'Înțelegerea bolii trofoblastice gestaționale',
      overviewText: 'BTG include mola hidatiformă și forme maligne numite împreună neoplazie trofoblastică gestațională, precum mola invazivă și coriocarcinomul. Aceste afecțiuni provin din celule legate de sarcină. Nivelul hCG din sânge este esențial pentru diagnostic și urmărire, iar tratamentul diferă de cel al cancerului uterin obișnuit.',
      symptomsTitle: 'Semne și simptome posibile',
      symptoms: ['Sângerare vaginală anormală în timpul sau după sarcină', 'Un uter mai mare decât este de așteptat pentru sarcină', 'Durere sau presiune pelvină', 'Greață și vărsături severe', 'Tensiune arterială foarte devreme în sarcină, cu dureri de cap ori umflături', 'Sângerare persistentă, lipsă de aer, amețeală ori oboseală marcată după sarcină'],
      treatmentsTitle: 'Tratament și îngrijire',
      treatmentsIntro: 'Tratamentul depinde de tipul exact, nivelul hCG, răspândire, sarcina anterioară și dorința de fertilitate. Urmărirea specializată este esențială până la finalizarea monitorizării hCG.',
      treatment1: {title: 'Evacuare uterină și monitorizare', desc: 'Sarcina molară este tratată de obicei prin îndepărtarea țesutului anormal din uter, urmată de teste hCG regulate pentru confirmarea dispariției activității trofoblastice.'},
      treatment2: {title: 'Chimioterapie sau chirurgie', desc: 'Neoplazia trofoblastică gestațională este tratată frecvent cu unul sau mai multe medicamente chimioterapice. Chirurgia ori alte tratamente pot fi folosite în cazuri selectate, rezistente sau recidivate.'},
    },
    es: {
      title: 'Enfermedad trofoblástica gestacional (ETG)',
      shortDescription: 'Un grupo de enfermedades raras causadas por crecimiento anormal de células trofoblásticas en el útero después de la concepción.',
      overviewTitle: 'Comprender la enfermedad trofoblástica gestacional',
      overviewText: 'La ETG incluye la mola hidatidiforme y formas malignas llamadas neoplasia trofoblástica gestacional, como la mola invasora y el coriocarcinoma. Surgen de células relacionadas con el embarazo. La hCG sanguínea es fundamental para diagnóstico y seguimiento, y el tratamiento difiere del cáncer uterino habitual.',
      symptomsTitle: 'Posibles signos y síntomas',
      symptoms: ['Sangrado vaginal anormal durante o después del embarazo', 'Útero mayor de lo esperado para la gestación', 'Dolor o presión pélvica', 'Náuseas y vómitos intensos', 'Presión alta muy temprana con cefalea o hinchazón', 'Sangrado persistente, falta de aire, mareo o cansancio marcado después del embarazo'],
      treatmentsTitle: 'Tratamiento y atención',
      treatmentsIntro: 'El tratamiento depende del tipo exacto, nivel de hCG, extensión, embarazo previo y deseos de fertilidad. El seguimiento especializado es esencial hasta completar la vigilancia de hCG.',
      treatment1: {title: 'Evacuación uterina y vigilancia', desc: 'El embarazo molar suele tratarse retirando el tejido anormal del útero, seguido de análisis regulares de hCG para confirmar que ya no hay actividad trofoblástica.'},
      treatment2: {title: 'Quimioterapia o cirugía', desc: 'La neoplasia trofoblástica gestacional suele tratarse con uno o más medicamentos de quimioterapia. La cirugía u otros tratamientos pueden utilizarse en casos seleccionados, resistentes o recurrentes.'},
    },
  },
  mds: {
    en: {
      title: 'Myelodysplastic Syndromes (MDS)',
      shortDescription: 'A group of bone-marrow cancers in which immature blood cells do not become enough healthy mature cells.',
      overviewTitle: 'Understanding MDS',
      overviewText: 'In MDS, abnormal stem cells in the bone marrow produce too few healthy red cells, white cells or platelets. The group includes several subtypes with different risks. Some remain stable for years, while others progress more quickly or develop into acute myeloid leukaemia. Blood counts, marrow findings and genetic changes guide risk assessment.',
      symptomsTitle: 'Possible signs and symptoms',
      symptoms: ['Persistent tiredness or weakness', 'Shortness of breath', 'Skin that is paler than usual', 'Frequent or unusual infections', 'Easy bruising or bleeding', 'Pinpoint red or purple spots under the skin'],
      treatmentsTitle: 'Treatment and care',
      treatmentsIntro: 'Treatment depends on subtype, blood counts, genetic findings, symptoms, progression risk, age and overall health. Some people initially need monitoring only.',
      treatment1: {title: 'Supportive care', desc: 'Blood or platelet transfusions, medicines that stimulate blood-cell production, antibiotics and iron-overload management may reduce complications from low blood counts.'},
      treatment2: {title: 'Disease-modifying treatment', desc: 'Medicines such as azacitidine, decitabine, lenalidomide, immunosuppressive treatment or chemotherapy may be used. Donor stem-cell transplant is a potentially curative option for selected people.'},
    },
    ro: {
      title: 'Sindroame mielodisplazice (SMD)',
      shortDescription: 'Un grup de cancere ale măduvei osoase în care celulele sanguine imature nu formează suficiente celule mature sănătoase.',
      overviewTitle: 'Înțelegerea SMD',
      overviewText: 'În SMD, celulele stem anormale din măduva osoasă produc prea puține globule roșii, globule albe sau trombocite sănătoase. Există mai multe subtipuri cu riscuri diferite. Unele rămân stabile ani, iar altele progresează sau se transformă în leucemie mieloidă acută. Hemograma, măduva și modificările genetice ghidează evaluarea.',
      symptomsTitle: 'Semne și simptome posibile',
      symptoms: ['Oboseală sau slăbiciune persistentă', 'Lipsă de aer', 'Piele mai palidă decât de obicei', 'Infecții frecvente sau neobișnuite', 'Vânătăi ori sângerări ușoare', 'Puncte roșii sau violacee mici sub piele'],
      treatmentsTitle: 'Tratament și îngrijire',
      treatmentsIntro: 'Tratamentul depinde de subtip, hemogramă, rezultate genetice, simptome, risc de progresie, vârstă și starea generală. Unele persoane necesită inițial doar monitorizare.',
      treatment1: {title: 'Îngrijire de susținere', desc: 'Transfuziile de sânge sau trombocite, medicamentele care stimulează producția celulelor sanguine, antibioticele și controlul supraîncărcării cu fier pot reduce complicațiile.'},
      treatment2: {title: 'Tratament care modifică boala', desc: 'Pot fi folosite azacitidina, decitabina, lenalidomida, tratamentul imunosupresor ori chimioterapia. Transplantul de celule stem de la donator poate vindeca unele persoane selectate.'},
    },
    es: {
      title: 'Síndromes mielodisplásicos (SMD)',
      shortDescription: 'Un grupo de cánceres de médula ósea en los que las células inmaduras no producen suficientes células sanguíneas maduras sanas.',
      overviewTitle: 'Comprender los SMD',
      overviewText: 'En los SMD, células madre anormales de la médula producen muy pocos glóbulos rojos, blancos o plaquetas sanos. Hay varios subtipos con riesgos distintos. Algunos permanecen estables durante años y otros progresan o se transforman en leucemia mieloide aguda. Los recuentos, la médula y los cambios genéticos orientan el riesgo.',
      symptomsTitle: 'Posibles signos y síntomas',
      symptoms: ['Cansancio o debilidad persistentes', 'Falta de aire', 'Piel más pálida de lo habitual', 'Infecciones frecuentes o inusuales', 'Moretones o sangrado fáciles', 'Puntos rojos o morados pequeños bajo la piel'],
      treatmentsTitle: 'Tratamiento y atención',
      treatmentsIntro: 'El tratamiento depende del subtipo, recuentos, genética, síntomas, riesgo de progresión, edad y salud general. Algunas personas inicialmente solo necesitan vigilancia.',
      treatment1: {title: 'Cuidados de apoyo', desc: 'Transfusiones, medicamentos que estimulan células sanguíneas, antibióticos y control de sobrecarga de hierro pueden reducir complicaciones de los recuentos bajos.'},
      treatment2: {title: 'Tratamiento modificador de la enfermedad', desc: 'Pueden utilizarse azacitidina, decitabina, lenalidomida, tratamiento inmunosupresor o quimioterapia. El trasplante de células madre de donante puede ser curativo en personas seleccionadas.'},
    },
  },
  mpn: {
    en: {
      title: 'Myeloproliferative Neoplasms (MPNs)',
      shortDescription: 'A group of chronic blood cancers in which the bone marrow makes too many blood cells.',
      overviewTitle: 'Understanding MPNs',
      overviewText: 'MPNs arise from an abnormal blood-forming stem cell and cause excess production of one or more blood-cell types. This guide focuses on polycythaemia vera, essential thrombocythaemia and primary myelofibrosis. They differ in symptoms and risks but can cause blood clots, bleeding, an enlarged spleen or, less often, transformation to acute leukaemia.',
      symptomsTitle: 'Possible signs and symptoms',
      symptoms: ['Headache, dizziness or visual changes', 'Itching, especially after warm water', 'Unusual bruising, bleeding or clot-related symptoms', 'Fullness or pain under the left ribs from an enlarged spleen', 'Persistent fatigue, bone pain or weakness', 'Night sweats, fever or unexplained weight loss'],
      treatmentsTitle: 'Treatment and care',
      treatmentsIntro: 'Treatment depends on the exact MPN, age, symptoms, blood counts, clotting history, molecular findings and progression risk. Regular haematology follow-up is essential.',
      treatment1: {title: 'Blood-count and clot-risk control', desc: 'Monitoring, phlebotomy, clinician-directed antiplatelet treatment and medicines that reduce blood-cell production may be used according to the subtype and individual risk.'},
      treatment2: {title: 'Targeted and advanced treatment', desc: 'Targeted medicines, symptom-directed therapy, transfusions or other treatments may be needed. Donor stem-cell transplant is considered for selected people with higher-risk myelofibrosis or transformation.'},
    },
    ro: {
      title: 'Neoplasme mieloproliferative (NMP)',
      shortDescription: 'Un grup de cancere cronice ale sângelui în care măduva osoasă produce prea multe celule sanguine.',
      overviewTitle: 'Înțelegerea NMP',
      overviewText: 'NMP pornesc dintr-o celulă stem hematopoietică anormală și determină producția excesivă a unuia sau mai multor tipuri de celule. Ghidul se concentrează pe policitemia vera, trombocitemia esențială și mielofibroza primară. Acestea pot provoca cheaguri, sângerări, splină mărită sau, mai rar, transformare în leucemie acută.',
      symptomsTitle: 'Semne și simptome posibile',
      symptoms: ['Dureri de cap, amețeală sau schimbări ale vederii', 'Mâncărime, mai ales după contactul cu apă caldă', 'Vânătăi, sângerări ori simptome de cheag neobișnuite', 'Senzație de plenitudine sau durere sub coastele stângi', 'Oboseală persistentă, durere osoasă sau slăbiciune', 'Transpirații nocturne, febră ori scădere inexplicabilă în greutate'],
      treatmentsTitle: 'Tratament și îngrijire',
      treatmentsIntro: 'Tratamentul depinde de tipul exact, vârstă, simptome, hemogramă, istoricul de tromboze, rezultatele moleculare și riscul de progresie. Urmărirea hematologică regulată este esențială.',
      treatment1: {title: 'Controlul hemogramei și riscului de cheag', desc: 'În funcție de subtip și risc pot fi folosite monitorizarea, flebotomia, tratamentul antiagregant indicat de medic și medicamente care reduc producția celulelor sanguine.'},
      treatment2: {title: 'Tratament țintit și avansat', desc: 'Pot fi necesare medicamente țintite, tratament pentru simptome, transfuzii sau alte opțiuni. Transplantul de celule stem de la donator este luat în considerare pentru mielofibroză cu risc înalt ori transformare.'},
    },
    es: {
      title: 'Neoplasias mieloproliferativas (NMP)',
      shortDescription: 'Un grupo de cánceres sanguíneos crónicos en los que la médula ósea produce demasiadas células de la sangre.',
      overviewTitle: 'Comprender las NMP',
      overviewText: 'Las NMP surgen de una célula madre sanguínea anormal y causan producción excesiva de uno o más tipos de células. Esta guía se centra en policitemia vera, trombocitemia esencial y mielofibrosis primaria. Pueden causar coágulos, sangrado, bazo agrandado o, con menor frecuencia, transformación a leucemia aguda.',
      symptomsTitle: 'Posibles signos y síntomas',
      symptoms: ['Dolor de cabeza, mareo o cambios visuales', 'Picor, especialmente después de agua caliente', 'Moretones, sangrado o síntomas de coágulo inusuales', 'Llenura o dolor bajo las costillas izquierdas', 'Cansancio persistente, dolor óseo o debilidad', 'Sudores nocturnos, fiebre o pérdida de peso sin explicación'],
      treatmentsTitle: 'Tratamiento y atención',
      treatmentsIntro: 'El tratamiento depende del tipo exacto, edad, síntomas, recuentos, antecedentes de trombosis, hallazgos moleculares y riesgo de progresión. El seguimiento hematológico regular es esencial.',
      treatment1: {title: 'Control de recuentos y riesgo de coágulo', desc: 'Según el subtipo y riesgo pueden usarse vigilancia, flebotomía, tratamiento antiagregante indicado por el médico y medicamentos que reducen la producción de células sanguíneas.'},
      treatment2: {title: 'Tratamiento dirigido y avanzado', desc: 'Pueden necesitarse medicamentos dirigidos, tratamiento sintomático, transfusiones u otras opciones. El trasplante de células madre de donante se considera en mielofibrosis de alto riesgo o transformación.'},
    },
  },
};

export function getAdditionalCancerGuideBatch2Content(
  cancerId: CancerId | string,
  localeInput: string,
): AdditionalCancerGuideContent | undefined {
  if (!(cancerId in CONTENT)) return undefined;
  const locale = normalizeLocale(localeInput);
  return CONTENT[cancerId as Batch2CancerGuideId][locale];
}
